---
- name: Apache server installed
  hosts: all
  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest 

  - name: Enable and Start Apache
    service:
      name: httpd
      enabled: true
      state: started
      
     

      
      
