---
- name: Set selinux boolean
  hosts: all
  #vars:
   # selinux_policy: targeted
    #selinux_state: enforcing
  tasks:
  - name: set SElinux to enforcing  
    linux-system-roles.selinux:
      selinux_policy: targeted
      selinux_state: enforcing
 
