---
- name: Set selinux boolean
  hosts: all
  tasks:
    - name: Set SELinux to enforcing
      include_role:
        name: fedora.linux_system_roles.selinux
      vars:
        selinux_state: enforcing

 
